In [1]:
import tensorflow as tf

In [2]:
import numpy as np
import pandas as pd

In [3]:
tf.__version__

'2.1.0'

In [5]:
dataset = pd.read_csv('Churn_Modelling.csv')
X=dataset.iloc[:,3:-1].values
Y=dataset.iloc[:,-1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(Y)

[1 0 1 ... 1 1 0]


### Encoding 

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2]= le.fit_transform(X[:,2])

In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### One hot encoding

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### splitting data set 

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train,Y_test = train_test_split(X,Y, test_size = 0.2, random_state =0
                                                 )

### Feature Scaling

In [13]:
 from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

## Building the ANN

In [17]:
#initialization of Artificial neural network
ann = tf.keras.models.Sequential()

In [25]:
#Adding input and the first hidden layer
ann.add(tf.keras.layers.Dense(units=8,activation='relu'))

In [26]:
#adding the second layer
ann.add(tf.keras.layers.Dense(units=8,activation='relu'))

In [27]:
#Adding the output layer
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid')) 

## Training the ANN

In [28]:
#compiling the ann
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [29]:
#Training the ann on training set
ann.fit(X_train, Y_train, batch_size = 64, epochs = 200)


Train on 8000 samples
Epoch 1/200
8000/8000 [==============================] - 1s 134us/sample - loss: 0.6645 - accuracy: 0.7959
Epoch 2/200
8000/8000 [==============================] - 0s 35us/sample - loss: 0.6191 - accuracy: 0.8594
Epoch 3/200
8000/8000 [==============================] - 0s 32us/sample - loss: 0.5121 - accuracy: 0.8615
Epoch 4/200
8000/8000 [==============================] - 0s 31us/sample - loss: 0.4048 - accuracy: 0.8625
Epoch 5/200
8000/8000 [==============================] - 0s 31us/sample - loss: 0.3638 - accuracy: 0.8624
Epoch 6/200
8000/8000 [==============================] - 0s 33us/sample - loss: 0.3498 - accuracy: 0.8618
Epoch 7/200
8000/8000 [==============================] - 0s 34us/sample - loss: 0.3453 - accuracy: 0.8630
Epoch 8/200
8000/8000 [==============================] - 0s 32us/sample - loss: 0.3438 - accuracy: 0.8626
Epoch 9/200
8000/8000 [==============================] - 0s 31us/sample - loss: 0.3417 - accuracy: 0.8630
Epoch 10/200
8000/8000 

8000/8000 [==============================] - 0s 31us/sample - loss: 0.3336 - accuracy: 0.8626
Epoch 78/200
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3329 - accuracy: 0.8622
Epoch 79/200
8000/8000 [==============================] - 0s 31us/sample - loss: 0.3325 - accuracy: 0.8629
Epoch 80/200
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3333 - accuracy: 0.8645
Epoch 81/200
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3331 - accuracy: 0.8648
Epoch 82/200
8000/8000 [==============================] - 0s 31us/sample - loss: 0.3328 - accuracy: 0.8615
Epoch 83/200
8000/8000 [==============================] - 0s 31us/sample - loss: 0.3329 - accuracy: 0.8636
Epoch 84/200
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3325 - accuracy: 0.8640
Epoch 85/200
8000/8000 [==============================] - 0s 31us/sample - loss: 0.3330 - accuracy: 0.8645
Epoch 86/200
8000/8000 [==========================

8000/8000 [==============================] - 0s 31us/sample - loss: 0.3298 - accuracy: 0.8641
Epoch 154/200
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3297 - accuracy: 0.8655
Epoch 155/200
8000/8000 [==============================] - 0s 31us/sample - loss: 0.3303 - accuracy: 0.8651
Epoch 156/200
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3304 - accuracy: 0.8637
Epoch 157/200
8000/8000 [==============================] - 0s 31us/sample - loss: 0.3299 - accuracy: 0.8645
Epoch 158/200
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3303 - accuracy: 0.8644
Epoch 159/200
8000/8000 [==============================] - 0s 32us/sample - loss: 0.3298 - accuracy: 0.8652
Epoch 160/200
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3293 - accuracy: 0.8668
Epoch 161/200
8000/8000 [==============================] - 0s 31us/sample - loss: 0.3302 - accuracy: 0.8641
Epoch 162/200
8000/8000 [=================

## Making the prediction and evaluating

In [30]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))

array([[0.02709289]], dtype=float32)

In [32]:
#predicting the test set result
Y_pred = ann.predict(X_test)
Y_pred = (Y_pred > 0.5)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm =confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[1504   91]
 [ 199  206]]


0.855